### ISSUE TITLE
Create `.env.sample` for environment variables

### ISSUE THREAD

**Issue by ajcwebdev** [stepzen-samples/stepzen-nuxt#1]
File will have the format:

```
STEPZEN_API_KEY={{STEPZEN_API_KEY}}
STEPZEN_ENDPOINT={{STEPZEN_ENDPOINT}}
```

Also include instructions in the `README.md` for creating your own for local development with:

```bash
cp .env.sample .env
```

**Comment by virtuoushub** [comment]
🌊 Hello, I will claim this issue.

I ran into having to do this step when setting up the project just now and I have a couple suggestions to speed up onboarding.

1. Check-in a `stepzen.config.json` that looks similar to:

```json
{
  "endpoint": "api/stepzen-nuxt",
  "root": "stepzen/schema"
}
```

2. Update `components/NuxtMountains.vue` to use the variables read from the `.env` file

```js
...
      this.mountains = await fetch(
        `${process.env.REACT_APP_STEPZEN_ENDPOINT}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `apikey ${process.env.REACT_APP_STEPZEN_API_KEY}`
          },
...
```

@ajcwebdev - any comments/concerns w/ this approach?

**Comment by ajcwebdev** [comment]
Looks good, thanks a lot @virtuoushub 👍

Merged https://github.com/stepzen-samples/stepzen-nuxt/pull/10
